# See [Connector Acceptance Tests](https://docs.airbyte.com/connector-development/testing-connectors/connector-acceptance-tests-reference)
# for more information about how to configure these tests
connector_image: planetscale/airbyte-source:latest
acceptance_tests:
  spec:
    tests:
      - spec_path: "source_planetscale/spec.yaml"
